import {
  BookOpenIcon,
  BrushIcon,
  CakeIcon,
  CameraIcon,
  CarIcon,
  CrownIcon,
  FeatherIcon,
  Flower2Icon,
  GemIcon,
  GlobeIcon,
  HandHeartIcon,
  LayersIcon,
  PackageIcon,
  PartyPopperIcon,
  RibbonIcon,
  ScissorsIcon,
  ShirtIcon,
  UsersIcon,
  UtensilsIcon,
  VideoIcon,
  type LucideIcon,
} from "lucide-react";
import type { VendorCategory } from "@/lib/vendors/catalog";

/** Icône de chaque catégorie, dans le menu et la vue d'ensemble. */
export const VENDOR_ICONS: Record<VendorCategory, LucideIcon> = {
  catering: UtensilsIcon,
  florist: Flower2Icon,
  cake: CakeIcon,
  hair: ScissorsIcon,
  makeup: BrushIcon,
  beauty: HandHeartIcon,
  officiant: BookOpenIcon,
  car: CarIcon,
  entertainment: PartyPopperIcon,
  guest_gifts: PackageIcon,
  rings: GemIcon,
  photographer: CameraIcon,
  videographer: VideoIcon,
  bridal_gown: CrownIcon,
  bridesmaids: RibbonIcon,
  groom_suit: ShirtIcon,
  groomsmen: UsersIcon,
  stationery: FeatherIcon,
  website: GlobeIcon,
  other: LayersIcon,
};
